name: Generate SBOM
description: A GitHub Action to generate SBOM using CycloneDX and upload it to Dependency Track.
permissions:
  contents: read

inputs:
  node_version:
    description: 'Node.js version to setup'
    required: true
    default: '20'
  server_hostname:
    description: 'Dependency Track server hostname'
    required: true
  api_key:
    description: 'API key for Dependency Track'
    required: true
  project_name:
    description: 'Project name for Dependency Track'
    required: true
  project_version:
    description: 'Project version for Dependency Track'
    required: true
  bom_filename:
    description: 'Filename for the BOM'
    required: false
    default: './bom/bom.xml'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
         
    - name: Install Yarn
      run: npm install -g yarn
      shell: bash
          
    - name: Install packages
      run: yarn install
      shell: bash
      
    - name: Setup Node.js with Yarn caching
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'
        
     - name: Install packages
      run: yarn install --ignore-scripts
      shell: bash
  
    - name: Create BOM directory
      run: mkdir -p bom
      shell: bash 

    - name: Create SBOM with CycloneDX
      uses: CycloneDX/gh-node-module-generatebom@v1
      with: 
        output: ${{ inputs.bom_filename }}

    - name: Upload BOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: bom-artifact
        path: ${{ inputs.bom_filename }}
          
    - name: Download BOM artifact
      uses: actions/download-artifact@v4
      with:
        name: bom-artifact

    - name: Upload BOM to Dependency Track
      uses: DependencyTrack/gh-upload-sbom@v3
      with:
        serverHostname: ${{ inputs.server_hostname }}
        apiKey: ${{ inputs.api_key }}
        protocol: https
        projectName: ${{ inputs.project_name }}
        projectVersion: ${{ inputs.project_version }}
        bomFilename: ${{ inputs.bom_filename }}
        autoCreate: true
